apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app2-data-pvc
  namespace: clawtest
  labels:
    app: app2
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      alicloud-pvname: nas-test
  storageClassName: nas
  volumeMode: Filesystem
  volumeName: nas-test
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app2-log-pvc
  namespace: clawtest
  labels:
    app: app2
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      alicloud-pvname: nas-test
  storageClassName: nas
  volumeMode: Filesystem
  volumeName: nas-test
