apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app2-data-pvc
  namespace: clawtest
  labels:
    app: app2
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
  selector:
    matchLabels:
      alicloud-pvname: nas-test
  storageClassName: nas
  volumeMode: Filesystem
  volumeName: nas-test
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: 'yes'
  labels:
    alicloud-pvname: perf-test1-app2-nas-pv
  name: perf-test1-app2-nas-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 20Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: test
    namespace: default
    resourceVersion: '92635'
    uid: 16a0b57a-c82e-4f86-a4f2-c9edc67ca0e7
  csi:
    driver: nasplugin.csi.alibabacloud.com
    volumeAttributes:
      path: ''
      server: 121ctz5eqhxpbd0gglg-qac32.cn-hongkong.nas.aliyuncs.com
    volumeHandle: nas-test
  mountOptions:
    - 'nolock,tcp,noresvport'
    - vers=3
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nas
  volumeMode: Filesystem
status:
  lastPhaseTransitionTime: '2026-06-09T04:27:31Z'
  phase: Bound
