apiVersion: v1
kind: Service
metadata:
  name: perf-test1-app876-svc
  namespace: clawtest
  labels:
    app: perf-test1-app876
spec:
  selector:
    app: perf-test1-app876
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
